name: terreiro_queue_system
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.5.4
  fl_chart: ^0.68.0

  # Firebase
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.0

  # Serialization
  json_annotation: ^4.9.0

  # Plugin Local
  gertec_pos_printer:
    path: ./plugins/gertec_pos_printer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/wood_background.jpg
    - assets/images/kiosk_bg_selection.jpg
    - assets/images/linhas/
